<?php

namespace App\Jobs;

use App\Actions\ProposeArticle;
use App\Models\Article;
use App\Models\EditorialPolicy;
use App\Models\Material;
use App\Models\Prompt;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Queue\Queueable;
use RuntimeException;
use Throwable;

/**
 * 記事を生成 (UI: "Generate article", stage 2.4 of docs/HANDOVER.md): an
 * article is made in three steps, each in the background. The headline
 * comes first, from the material (App\Jobs\RefineHeadline); this job then
 * has the agent write the body under that headline per the article
 * generation layer of the editorial policy, checks that a body came back,
 * and keeps it; the translations follow. The article pins the prompt
 * versions and the models it was written with and keeps the usage of the
 * body's call, as a screening and a material do. The outcome lands on the
 * article (status 生成中 / 下書き / 失敗) so the screens can show it.
 */
class GenerateArticle implements ShouldQueue
{
    use Queueable;

    public int $tries = 1;

    public int $timeout = 300;

    public function __construct(public Article $article) {}

    /**
     * Queue the writing of a material's article: the row appears at once
     * as 生成中, whether it is new or being written again, and the
     * headline is written first; this job follows it. This is the
     * original — the one written from the material, in the language of
     * the primary source — so it is the material's article that has no
     * article behind it; the translations are queued once it is written.
     */
    public static function queueFor(Material $material): Article
    {
        $article = Article::query()->updateOrCreate(
            ['material_id' => $material->id, 'translated_from_id' => null],
            [
                'status' => 'generating',
                'status_message' => null,
                'prompt_id' => Prompt::current('article', EditorialPolicy::bodyFor('article'))->id,
                'model' => EditorialPolicy::modelFor('article'),
            ],
        );

        return RefineHeadline::queueFor($article);
    }

    public function handle(ProposeArticle $propose): void
    {
        $article = $this->article;
        $material = $article->material;

        try {
            if ($material === null || $material->status !== 'extracted' || $material->data === null) {
                throw new RuntimeException(__('The material has not been extracted yet.'));
            }

            if (trim((string) $article->title) === '') {
                throw new RuntimeException(__('The headline has not been written yet.'));
            }

            // The policy read is the version pinned when the job was queued, not whatever the screen holds by now.
            $policy = $article->prompt !== null ? $article->prompt->text : '';

            if (trim($policy) === '') {
                throw new RuntimeException(__('The article generation layer of the editorial policy is empty.'));
            }

            $document = $material->document;
            $model = (string) $article->model;
            $result = $propose($policy, $model, (array) $material->data, (string) $article->title, $document->title, $document->url);
            $body = trim((string) ($result['json']['body'] ?? ''));

            if ($body === '') {
                throw new RuntimeException(__('The agent did not return a body.'));
            }

            $article->update([
                'body' => $body,
                // The language the agent says it wrote in, which is the material's and so the primary source's.
                'language' => in_array($result['json']['language'] ?? null, Article::SOURCE_LANGUAGES, true) ? $result['json']['language'] : null,
                'status' => 'draft',
                'status_message' => __('Generated by :model.', ['model' => $model]),
                ...$result['usage'],
                'estimated_total_cost' => ScreenDocument::estimatedCost($model, $result['usage'])['estimated_total_cost'],
            ]);
        } catch (Throwable $exception) {
            $article->update(['status' => 'failed', 'status_message' => mb_substr($exception->getMessage(), 0, 1000)]);

            return;
        }

        // Nothing waits for a person: the languages we publish in follow the written article.
        foreach ($article->refresh()->translationLanguages() as $language) {
            TranslateArticle::queueFor($article, $language);
        }
    }
}
