<?php

namespace App\Jobs;

use App\Actions\ProposeArticle;
use App\Models\Article;
use App\Models\EditorialPolicy;
use App\Models\Material;
use App\Models\Prompt;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Queue\Queueable;
use RuntimeException;
use Throwable;

/**
 * 記事を生成 (UI: "Generate article", stage 2.4 of docs/HANDOVER.md): in the
 * background, have the agent write an article from an extracted material
 * per the article generation layer of the editorial policy, check that a
 * title and a body came back, and keep them as the material's article.
 * The article pins the prompt version and the model it was written with
 * and keeps the usage of the call, as a screening and a material do.
 * The outcome lands on the article (status 生成中 / 下書き / 失敗) so the
 * screens can show it.
 */
class GenerateArticle implements ShouldQueue
{
    use Queueable;

    public int $tries = 1;

    public int $timeout = 300;

    public function __construct(public Article $article) {}

    /**
     * Queue the writing of a material's article: the row appears at once
     * as 生成中, whether it is new or being written again. This is the
     * original — the one written from the material, in the language of
     * the primary source — so it is the material's article that has no
     * article behind it; the translations are queued once it is written.
     */
    public static function queueFor(Material $material): Article
    {
        $article = Article::query()->updateOrCreate(
            ['material_id' => $material->id, 'translated_from_id' => null],
            [
                'status' => 'generating',
                'status_message' => null,
                'prompt_id' => Prompt::current('article', EditorialPolicy::bodyFor('article'))->id,
                'model' => EditorialPolicy::modelFor('article'),
            ],
        );

        self::dispatch($article);

        return $article;
    }

    public function handle(ProposeArticle $propose): void
    {
        $article = $this->article;
        $material = $article->material;

        try {
            if ($material === null || $material->status !== 'extracted' || $material->data === null) {
                throw new RuntimeException(__('The material has not been extracted yet.'));
            }

            // The policy read is the version pinned when the job was queued, not whatever the screen holds by now.
            $policy = $article->prompt !== null ? $article->prompt->text : '';

            if (trim($policy) === '') {
                throw new RuntimeException(__('The article generation layer of the editorial policy is empty.'));
            }

            $document = $material->document;
            $model = (string) $article->model;
            $result = $propose($policy, $model, (array) $material->data, $document->title, $document->url);
            $title = trim((string) ($result['json']['title'] ?? ''));
            $body = trim((string) ($result['json']['body'] ?? ''));

            if ($title === '' || $body === '') {
                throw new RuntimeException(__('The agent did not return a title and a body.'));
            }

            $article->update([
                'title' => $title,
                'body' => $body,
                // The language the agent says it wrote in, which is the material's and so the primary source's.
                'language' => in_array($result['json']['language'] ?? null, Article::SOURCE_LANGUAGES, true) ? $result['json']['language'] : null,
                'status' => 'draft',
                'status_message' => __('Generated by :model.', ['model' => $model]),
                ...$result['usage'],
                'estimated_total_cost' => ScreenDocument::estimatedCost($model, $result['usage'])['estimated_total_cost'],
            ]);
        } catch (Throwable $exception) {
            $article->update(['status' => 'failed', 'status_message' => mb_substr($exception->getMessage(), 0, 1000)]);

            return;
        }

        // The headline is scored and written again before anything is translated, so the translations carry the final one.
        RefineHeadline::queueFor($article->refresh());
    }
}
