<?php

namespace App\Jobs;

use App\Actions\ProposeArticle;
use App\Models\Article;
use App\Models\EditorialPolicy;
use App\Models\Material;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Queue\Queueable;
use RuntimeException;
use Throwable;

/**
 * 記事を生成 (UI: "Generate article", stage 2.4 of docs/HANDOVER.md): in the
 * background, have the agent write an article from an extracted material
 * per the article generation layer of the editorial policy, check that a
 * title and a body came back, and keep them as the material's article.
 * The outcome lands on the article (status 生成中 / 下書き / 失敗) so the
 * screens can show it.
 */
class GenerateArticle implements ShouldQueue
{
    use Queueable;

    public int $tries = 1;

    public int $timeout = 300;

    public function __construct(public Article $article) {}

    /**
     * Queue the generation for a material: its article row appears at once
     * as 生成中, whether it is new or being generated again. One article
     * per material for now; the output languages of docs/HANDOVER.md §3
     * will add more.
     */
    public static function queueFor(Material $material): Article
    {
        $article = Article::query()->updateOrCreate(
            ['material_id' => $material->id],
            ['status' => 'generating', 'status_message' => null],
        );

        self::dispatch($article);

        return $article;
    }

    public function handle(ProposeArticle $propose): void
    {
        $article = $this->article;
        $material = $article->material;

        try {
            if ($material === null || $material->status !== 'extracted' || $material->data === null) {
                throw new RuntimeException(__('The material has not been extracted yet.'));
            }

            $policy = EditorialPolicy::bodyFor('article');

            if (trim($policy) === '') {
                throw new RuntimeException(__('The article generation layer of the editorial policy is empty.'));
            }

            $document = $material->document;
            $proposal = $propose($policy, (array) $material->data, $document->title, $document->url);
            $title = trim((string) ($proposal['title'] ?? ''));
            $body = trim((string) ($proposal['body'] ?? ''));

            if ($title === '' || $body === '') {
                throw new RuntimeException(__('The agent did not return a title and a body.'));
            }

            $article->update(['title' => $title, 'body' => $body, 'status' => 'draft', 'status_message' => __('Generated by :model.', ['model' => (string) config('services.openai.model')])]);
        } catch (Throwable $exception) {
            $article->update(['status' => 'failed', 'status_message' => mb_substr($exception->getMessage(), 0, 1000)]);
        }
    }
}
